EMAIL_XPATH = "//input[@name='email']"
PASSWORD_XPATH = "//input[@name='PASSWORD']"
REMEMBER_ME_XPATH = "//input[@name='rememberMe']"
PASSWORD_RECOVERY_XPATH = "//a[@href='/password-recovery']"
LOGIN_BTN_XPATH = "//button[@type='submit']"
